# This is the main configuration file for MultiPaper.
# There's quite alot to configure. Read the docs for more information.
#
# Docs: https://github.com/PureGero/MultiPaper/blob/main/MULTIPAPER_YAML.md 

useLocalPlayerCountForServerIsFullKick: false
syncJsonFiles: true
advertiseToBuiltInProxy: true
syncScoreboards: true
logFileSyncing: true
filesToSyncOnStartup:
- txt
filesToSyncInRealTime:
- plugins/MyPluginDirectory
filesToOnlyUploadOnServerStop:
- plugins/MyPluginDirectory/my_big_database.db
filesToNotSync:
- plugins/bStats
ticksPerInactiveEntityTracking: 1
interServerCompressionThreshold: 0
interServerConsolidationDelay: 0
