version: "3"
services:
  master:
    image: metacringer/watermelon:mc-master
    ports:
    - "25565:25565"
    networks:
      vpcbr:
        ipv4_address: 10.1.0.2
  slave0:
    image: metacringer/watermelon:mc-slave
    environment:
      - server_name=slave0
    depends_on:
    - master
    networks:
      vpcbr:
        ipv4_address: 10.1.0.3
  slave1:
    image: metacringer/watermelon:mc-slave
    environment:
      - server_name=slave1
    depends_on:
    - master
    networks:
      vpcbr:
        ipv4_address: 10.1.0.4
networks:
  vpcbr:
    driver: overlay
    ipam:
     config:
       - subnet: 10.1.0.0/16
  
