apiVersion: v1
kind: ConfigMap
metadata:
  name: master-configmap
data:
{{ $currentScope := . -}}
{{- range $path, $_ :=  .Files.Glob  "config/master/*" -}}
{{- base $path | indent 2 -}}: |-
{{ with $currentScope -}}
{{ tpl (.Files.Get $path) .  | indent 4 -}}
{{- end }}
{{ end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slave-configmap
data:
{{ $currentScope := . -}}
{{- range $path, $_ :=  .Files.Glob  "config/slave/*" -}}
{{- base $path | indent 2 -}}: |-
{{ with $currentScope -}}
{{ tpl (.Files.Get $path) .  | indent 4 -}}
{{- end }}
{{ end -}}

