apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-master
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-storage
  volumeName: pv-master