apiVersion: v1
kind: Service
metadata:
  name: mc-master
spec:
  clusterIP: "None"
  selector:
    app: mc-master
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: multipaper
      protocol: TCP
      port: 35353
      targetPort: 35353

{{range $i, $e := until (int .Values.slave.replicas)}}
---
apiVersion: v1
kind: Service
metadata:
  name: mc-slave-{{$i}}
spec:
  clusterIP: "None"
  selector:
    app: mc-slave-{{$i}}
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
{{end}}