apiVersion: v1
kind: Service
metadata:
  labels: 
    app: public-minecraft
  name: public-minecraft
spec:
  selector:
    app: mc-master
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
  type: LoadBalancer